DO $$ BEGIN ALTER TABLE actual_opening_hours ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE exceptional_hours ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE openings ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE regular_hours ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE exceptions ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN END; $$;
