DO $$ BEGIN ALTER TABLE openings RENAME COLUMN _id TO id; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE regular_hours RENAME COLUMN _id TO id; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE exceptions RENAME COLUMN _id TO id; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE exceptional_hours RENAME COLUMN _id TO id; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE actual_opening_hours RENAME COLUMN _id TO id; EXCEPTION WHEN OTHERS THEN END; $$;
