DO $$ BEGIN ALTER TABLE actual_opening_hours ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE exceptional_hours ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE openings ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE regular_hours ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE exceptions ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;

DO $$ BEGIN ALTER TABLE audit_actual_opening_hours ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE audit_exceptional_hours ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE audit_openings ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE audit_regular_hours ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN ALTER TABLE audit_exceptions ALTER COLUMN jsonb SET NOT NULL; EXCEPTION WHEN OTHERS THEN END; $$;
