openapi: 3.0.3
info:
  title: Calendar Opening Hours API
  version: v5.0
servers:
  - url: /
paths:
  /opening-hours/calendars:
    $ref: paths/opening-hours/calendars.yaml
  /opening-hours/calendars/{calendarId}:
    $ref: paths/opening-hours/calendars/calendarIdSingle.yaml
  /opening-hours/calendars/{calendarId*}:
    $ref: paths/opening-hours/calendars/calendarIdMultiple.yaml
  /opening-hours/dates/{servicePointId}/adjacent-openings/{date}:
    $ref: paths/opening-hours/dates/adjacent-openings.yaml
  /opening-hours/dates/{servicePointId}/all-openings:
    $ref: paths/opening-hours/dates/all-openings.yaml
