openapi: 3.0.3
info:
  title: Calendar Opening Hours API
  version: v5.0
servers:
  - url: /
paths:
  /opening-hours/calendars:
    $ref: paths/opening-hours/calendars.yaml
  # /opening-hours/calendars/{calendarId*}:
  #   $ref: paths/opening-hours/calendars/calendarId.yaml
  # /opening-hours/adjacent-openings:
  #   $ref: paths/opening-hours/adjacent-openings.yaml
