#%RAML 0.8
title: Calendar
version: v1
baseUri: https://github.com/folio-org/mod-calendar

documentation:
  - title: mod-calendar API
    content: This module provides a backend for the calendar functionalities

schemas:
  - OpeningPeriod.json: !include schemas/OpeningPeriod.json
  - OpeningPeriodCollection: !include schemas/OpeningPeriodCollection.json
  - OpeningDay.json: !include schemas/OpeningDayIncludeWeekdays.json
  - OpeningHour.json: !include schemas/OpeningHour.json
  - Duration.json: !include schemas/Duration.json
  - Opening.json: !include schemas/Opening.json
  - Weekdays.json: !include schemas/Weekdays.json
  - OpeningDayWithDate.json: !include schemas/OpeningDayWithDate.json

/calendar:
  /openingperiod:
    /{servicepointId}:
      get:
        queryParameters:
          withPeriods:
            displayName: withPeriods
            type: boolean
            description: Include time periods in response. Default false.
            required: false
          withExceptions:
            displayName: withExceptions
            type: boolean
            description: Include exceptions in response. Default false.
            required: false
        description: List opening periods. The default response is the period names and it's dates.
        responses:
          200:
            body:
              application/json:
                schema: OpeningPeriodCollection
          404:
            description: "Not found"
          500:
            description: "Internal server error"
      post:
        body:
          application/json:
            schema: OpeningPeriod.json
        description: Saves the new OpeningPeriod
        responses:
          201:
            description: Returns with the created OpeningPeriod
            body:
              application/json:
                schema: OpeningPeriod.json
          400:
            description: "Bad request"
          500:
            description: "Internal server error"
      /lofasz/{openingPeriodId}:
        delete:
          description: Delete Opening period by Id
          responses:
            204:
             description: "Opening period deleted successfully"
            404:
              description: "Opening period with a given ID not found"
            400:
              description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
            500:
              description: "Internal server error, e.g. due to misconfiguration"
        put:
          description: update Opening period by id
          body:
            application/json:
                schema: OpeningPeriod.json
          responses:
            204:
              description: "Calendar successfully updated"
              body:
                application/json:
                  schema: OpeningPeriod.json
            404:
              description: "Calendar with a given ID not found"
            400:
              description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
            500:
              description: "Internal server error, e.g. due to misconfiguration"
      /calculateopening:
        get:
          queryParameters:
            date:
              displayName: date
              type: string
              description: date, start date
              example: 2017-05-24
              required: true
            isDays:
              displayName: isDays
              type: boolean
              description: Is it days
              required: false
            loanDays:
              displayName: loanDays
              type: integer
              description: number of loan days, to calculate due date. Can't use with loanHours parameter together.
              example: 11
              required: false
            includeClosedDays:
              displayName: includeClosedDays
              type: boolean
              description: included or excluded the closed days. Default value is false. Parameter is ignored if loanDays undefined.
              required: false
            loanHours:
              displayName: loanHours
              type: integer
              description: number of loan hours, to calculate due date. Can't use with loanDays parameter together.
              example: 60
              required: false
            includeClosedHours:
              displayName: includeClosedHours
              type: boolean
              description: included or excluded the closed hours. Default value is false. Parameter is ignored if loanHours undefined.
              required: false
          description: "This get responses three openings, these are the requested day, and it's next and previous dates openings.
          It's for asking a specified day opening and it responses the nearest opening days.
          Or for deciding that, the loan can be overnight or not.
          And for count the due day with given hour or day with the option to count the closed time."
          responses:
            200:
              body:
                application/json:
                  schema: Opening.json
            404:
              description: "Not found"
            500:
              description: "Internal server error"
      /calculateopeningduration:
        get:
          queryParameters:
            startTime:
              displayName: date
              type: string
              description: date, start date
              example: 2017-05-24
              required: false
            endTime:
              displayName: date
              type: string
              description: date, start date
              example: 2017-05-24
              required: true
            unit:
              displayName: isDays
              type: string
              enum:
                - day
                - hours
              description: Calculating days or hours.
              required: false
          description: This endpoint responses the number of opening day/hour between a time intervall.
          responses:
            200:
              body:
                application/json:
                  schema: Duration.json
            404:
              description: "Not found"
            500:
              description: "Internal server error"

